# Supabase Pooler Configuration
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.cfbqnseyraywennzqzyo
spring.datasource.password=makanaka144818

# JPA & Hibernate Settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false